### ISSUE TITLE
Page won't load

### ISSUE THREAD

**Issue by karindalziel** [CDRH/nebnews#45]
Just noting this for now, Not sure if other pages are affected. 

http://nebnewspapers.unl.edu/lccn/2010270501/1895-07-26/ed-1/seq-1/

**Comment by jduss4** [comment]
Ew.
![image](https://user-images.githubusercontent.com/2480492/34620052-ca513718-f209-11e7-816c-efd09a7ec08b.png)

"WandException Unable to decode image file"

**Comment by jduss4** [comment]
Note, there is an existing problem for this batch reported in the tracking spreadsheet

"Had to arrange the documents from three different places and change the lccns in hundreds of documents before I could finally get this to work. And then it turns out the LoC doesn't have an lccn for Hemingford Heralds -- it thinks that they are the Alliance Herald ahhhhhhh"

**Comment by jduss4** [comment]
The interesting news is that I have eisley and its tiffs sitting on my computer, so if we decided that we wanted to try regenerating jp2s and uploading them to the server, that's an option.

**Comment by karindalziel** [comment]
Moved to https://github.com/CDRH/open-oni_nebraska_theme/issues/32
